'use strict';

const Table   = require('cli-table3');
const { Dialect } = require('./dialect');
const chalk = require('chalk');
const fs = require('fs');
const path = require('path');

const MAX_CELL_WIDTH = 40;

/**
 * Format a query result as an ASCII table (like STRSQL display).
 */
function formatTable(result, opts = {}) {
  const { columns, rows, rowCount, elapsed, statement } = result;
  const effectiveRowCount = Number.isInteger(rowCount) && rowCount >= 0
    ? rowCount
    : Array.isArray(rows) ? rows.length : 0;
  const maxWidth = opts.maxCellWidth || MAX_CELL_WIDTH;
  const plain = Boolean(opts.plain);
  const asciiBorders = Boolean(opts.asciiBorders);

  if (!columns || columns.length === 0) {
    const msg = `(${effectiveRowCount} row${effectiveRowCount !== 1 ? 's' : ''} affected) - ${elapsed}ms`;
    return plain ? msg : chalk.yellow(`(${effectiveRowCount} row${effectiveRowCount !== 1 ? 's' : ''} affected) — ${elapsed}ms`);
  }

  const headers = columns.map(c =>
    plain
      ? truncate(c.name, maxWidth, { ascii: true })
      : chalk.bold.cyan(truncate(c.name, maxWidth))
  );

  const tableOpts = {
    head: headers,
    style: {
      head: [],
      border: plain ? [] : ['gray'],
    },
    wordWrap: false,
  };

  if (asciiBorders) {
    tableOpts.chars = {
      top: '-',
      'top-mid': '+',
      'top-left': '+',
      'top-right': '+',
      bottom: '-',
      'bottom-mid': '+',
      'bottom-left': '+',
      'bottom-right': '+',
      left: '|',
      'left-mid': '+',
      mid: '-',
      'mid-mid': '+',
      right: '|',
      'right-mid': '+',
      middle: '|',
    };
  }

  const table = new Table(tableOpts);

  for (const row of rows) {
    const cells = columns.map(c => {
      const val = row[c.name];
      if (val === null || val === undefined) return plain ? 'NULL' : chalk.dim('NULL');
      return truncate(String(val), maxWidth, { ascii: plain || asciiBorders });
    });
    table.push(cells);
  }

  const lines = [table.toString()];
  lines.push(
    plain
      ? `${effectiveRowCount} row${effectiveRowCount !== 1 ? 's' : ''} - ${elapsed}ms`
      : chalk.dim(`${effectiveRowCount} row${effectiveRowCount !== 1 ? 's' : ''} — ${elapsed}ms`)
  );
  return lines.join('\n');
}

/**
 * Format a non-SELECT result (INSERT/UPDATE/DELETE/CALL).
 */
function formatExecResult(result) {
  const { rowCount, elapsed } = result;
  return chalk.green(`✓ OK`) +
    chalk.dim(` — ${rowCount} row${rowCount !== 1 ? 's' : ''} affected, ${elapsed}ms`);
}

/**
 * Export result to CSV string.
 */
function toCSV(result) {
  const { columns, rows } = result;
  if (!columns || columns.length === 0) return '';

  const header = columns.map(c => csvEscape(c.name)).join(',');
  const dataRows = rows.map(row =>
    columns.map(c => {
      const val = row[c.name];
      return val === null || val === undefined ? '' : csvEscape(String(val));
    }).join(',')
  );

  return [header, ...dataRows].join('\r\n');
}

/**
 * Export result to formatted JSON string.
 */
function toJSON(result) {
  const { columns, rows, rowCount, elapsed, statement } = result;
  const data = rows.map(row => {
    const obj = {};
    for (const c of columns) {
      obj[c.name] = row[c.name] !== undefined ? row[c.name] : null;
    }
    return obj;
  });

  return JSON.stringify(
    { statement, rowCount, elapsed, columns: columns.map(c => c.name), rows: data },
    null,
    2
  );
}

/**
 * Export result as SQL INSERT statements.
 *
 * opts:
 *   table   {string}  target table name
 *   schema  {string}  optional schema prefix
 *   batch   {number}  rows per INSERT (multi-row VALUES, default 1)
 *   dialect {string|Dialect}  target DB type (default: 'ibmi')
 */
function toInsert(result, opts = {}) {
  const { columns, rows } = result;
  if (!columns || columns.length === 0) return '';

  const dialect   = opts.dialect instanceof Dialect ? opts.dialect : Dialect.for(opts.dialect || 'ibmi');
  const tableName = _qualifiedTable(opts);
  const colList   = columns.map(c => dialect.quoteId(c.name)).join(', ');
  const batchSize = Math.max(1, opts.batch || 1);

  const lines = [
    `-- Generated by strsql-node  ${new Date().toISOString()}`,
    `-- INSERT into ${tableName}  (${rows.length} rows)  dialect=${dialect.type}`,
    '',
  ];

  for (let i = 0; i < rows.length; i += batchSize) {
    const chunk = rows.slice(i, i + batchSize);
    const valueGroups = chunk.map(row => {
      const vals = columns.map(c => dialect.literal(row[c.name])).join(', ');
      return `  (${vals})`;
    });
    lines.push(`INSERT INTO ${tableName} (${colList})`);
    lines.push(`VALUES`);
    lines.push(valueGroups.join(',\n') + ';');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Export result as a SQL MERGE statement (upsert).
 *
 * opts:
 *   table   {string}    target table name  (required or inferred)
 *   schema  {string}    optional schema prefix
 *   keys    {string[]}  columns used as join keys for the ON clause (required)
 *
 * Generates DB2 for i compatible MERGE syntax.
 */
/**
 * Export result as upsert statements.
 * Syntax adapts to the target dialect:
 *   ibmi/db2/sqlserver → MERGE INTO ... USING (VALUES ...) ...
 *   postgresql/sqlite  → INSERT ... ON CONFLICT (...) DO UPDATE SET ...
 *   mysql              → INSERT ... ON DUPLICATE KEY UPDATE ...
 *   oracle             → MERGE INTO ... USING (SELECT ... FROM DUAL) ...
 *
 * opts:
 *   keys    {string[]}        key columns (required)
 *   table   {string}          target table name
 *   dialect {string|Dialect}  target DB type (default: 'ibmi')
 */
function toMerge(result, opts = {}) {
  const { columns, rows } = result;
  if (!columns || columns.length === 0) return '';

  const keys = opts.keys || [];
  if (keys.length === 0) throw new Error('toMerge() requires opts.keys.');

  const colNames = new Set(columns.map(c => c.name.toUpperCase()));
  for (const k of keys) {
    if (!colNames.has(k.toUpperCase()))
      throw new Error(`Key column "${k}" not found in result set.`);
  }

  const dialect   = opts.dialect instanceof Dialect ? opts.dialect : Dialect.for(opts.dialect || 'ibmi');
  const tableName = _qualifiedTable(opts);
  const cols      = columns.map(c => c.name);

  const lines = [
    `-- Generated by strsql-node  ${new Date().toISOString()}`,
    `-- UPSERT into ${tableName}  (${rows.length} rows)  keys: ${keys.join(', ')}  dialect=${dialect.type}  syntax=${dialect.upsertSyntax}`,
    '',
  ];

  for (const row of rows) {
    const vals = cols.map(c => row[c]);
    lines.push(dialect.upsert(tableName, cols, keys, vals) + ';');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Write result to a file. Format detected from extension.
 *
 * opts (for SQL exports):
 *   table  {string}    qualified table name  e.g. "MYLIB.ORDERS"
 *   keys   {string[]}  key columns for MERGE
 *   batch  {number}    rows per INSERT statement (multi-row VALUES)
 */
function exportToFile(result, filePath, opts = {}) {
  const ext = path.extname(filePath).toLowerCase();
  let content;

  if (ext === '.json') {
    content = toJSON(result);
  } else if (ext === '.csv') {
    content = toCSV(result);
  } else if (ext === '.insert.sql' || ext === '.inserts.sql' ||
             (ext === '.sql' && opts.sqlMode === 'insert')) {
    content = toInsert(result, opts);
  } else if (ext === '.merge.sql' ||
             (ext === '.sql' && opts.sqlMode === 'merge')) {
    content = toMerge(result, opts);
  } else if (ext === '.sql') {
    // Default .sql → INSERT
    content = toInsert(result, opts);
  } else {
    throw new Error(
      `Unsupported format: ${ext}. Use .csv, .json, .sql, .insert.sql, or .merge.sql`
    );
  }

  fs.writeFileSync(filePath, content, 'utf8');
  return content.length;
}

// ─── helpers ─────────────────────────────────────────────────────────────────

function truncate(str, max, opts = {}) {
  if (str.length <= max) return str;
  if (opts.ascii) {
    if (max <= 3) return '.'.repeat(Math.max(0, max));
    return str.slice(0, max - 3) + '...';
  }
  return str.slice(0, max - 1) + '…';
}

function csvEscape(val) {
  if (val.includes(',') || val.includes('"') || val.includes('\n')) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

/**
 * Convert a JS value to a DB2-compatible SQL literal.
 * - null/undefined  → NULL
 * - number/boolean  → unquoted
 * - Date            → 'YYYY-MM-DD' or TIMESTAMP '...'
 * - string          → single-quoted, single-quotes escaped
 */
function _sqlLiteral(val) {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number' || typeof val === 'boolean') return String(val);
  if (val instanceof Date) {
    // Full timestamp or date-only depending on time component
    const iso = val.toISOString();
    if (val.getHours() === 0 && val.getMinutes() === 0 && val.getSeconds() === 0) {
      return `'${iso.slice(0, 10)}'`;
    }
    return `TIMESTAMP '${iso.replace('T', ' ').replace('Z', '')}'`;
  }
  // String — escape single quotes by doubling them
  return `'${String(val).replace(/'/g, "''")}'`;
}

/**
 * Build a fully-qualified table name from opts.
 * opts.table can be "SCHEMA.TABLE" or just "TABLE".
 * opts.schema adds a prefix if opts.table has no dot.
 */
function _qualifiedTable(opts) {
  const table  = opts.table  || 'TARGET_TABLE';
  const schema = opts.schema || null;
  if (table.includes('.') || !schema) return table;
  return `${schema}.${table}`;
}

module.exports = {
  formatTable,
  formatExecResult,
  toCSV,
  toJSON,
  toInsert,
  toMerge,
  exportToFile,
};
