'use strict';

const { ERROR_MODE } = require('./importer');
const { Dialect }   = require('./dialect');

// ─── PipeResult ───────────────────────────────────────────────────────────────

class PipeResult {
  constructor() {
    this.totalFetched = 0;
    this.totalWritten = 0;
    this.totalSkipped = 0;
    this.errors       = [];   // [{ page, row, sql, error }]
    this.pages        = 0;
    this.dryRun       = false;
    this.elapsed      = 0;
    this.ddlExecuted  = false;
    this.truncated    = false;
  }

  summary() {
    const icon   = this.errors.length === 0 ? '✓' : '⚠';
    const dry    = this.dryRun ? ' [DRY RUN]' : '';
    const extras = [
      this.ddlExecuted ? 'DDL:yes' : null,
      this.truncated   ? 'truncated:yes' : null,
    ].filter(Boolean).join('  ');
    return (
      `${icon} Pipe complete${dry}  ` +
      `fetched=${this.totalFetched}  written=${this.totalWritten}  ` +
      `skipped=${this.totalSkipped}  errors=${this.errors.length}  ` +
      `pages=${this.pages}  elapsed=${this.elapsed}ms` +
      (extras ? `  ${extras}` : '')
    );
  }
}

// ─── DDL helpers ──────────────────────────────────────────────────────────────

/**
 * Generate a CREATE TABLE statement for the target database.
 * Uses the target dialect for type mapping, identifier quoting, and NULL syntax.
 *
 * @param {string}  targetTable    qualified target table name
 * @param {object}  describeResult result from conn.describeTable()
 * @param {string|Dialect} [dialectOrType='ibmi']  target DB dialect
 */
function generateDDL(targetTable, describeResult, dialectOrType) {
  const dialect = dialectOrType instanceof Dialect
    ? dialectOrType
    : Dialect.for(dialectOrType || 'ibmi');

  const cols = describeResult.rows.map(row => {
    const name    = dialect.quoteId(row.COLUMN_NAME);
    const srcType = row.DATA_TYPE || row.dataType || '';
    const len     = row.LENGTH       || row.columnSize  || 0;
    const scale   = row.NUMERIC_SCALE || 0;
    const typeStr = dialect.mapType(srcType, len, scale);
    const nullStr = dialect.nullableSuffix(row);
    const defVal  = row.COLUMN_DEFAULT ? ` DEFAULT ${row.COLUMN_DEFAULT}` : '';
    return `  ${name} ${typeStr}${defVal} ${nullStr}`.trimEnd();
  });

  return (
    `-- DDL generated by strsql-node  ${new Date().toISOString()}\n` +
    `-- target dialect: ${dialect.type}\n` +
    `CREATE TABLE ${targetTable} (\n` +
    cols.join(',\n') +
    '\n);'
  );
}

// ─── Pipe class ───────────────────────────────────────────────────────────────

/**
 * Streams rows from a source DB2 connection to a target DB2 connection.
 *
 * opts:
 *   sourceTable   {string}    qualified source table  e.g. "SRCLIB.ORDERS"
 *   targetTable   {string}    qualified target table  (default: same as sourceTable)
 *   sourceSQL     {string}    override: full SELECT to run on source (ignores sourceTable/where)
 *   where         {string}    optional WHERE clause appended to source SELECT
 *   mode          {string}    'insert' | 'merge'   (default: 'insert')
 *   keys          {string[]}  key columns for MERGE ON clause (required if mode='merge')
 *   mapping       {object}    { srcCol: destCol, ... }  rename/filter columns
 *   batchSize     {number}    rows fetched and written per page (default: 500)
 *   pageSize      {number}    alias for batchSize
 *   truncate      {boolean}   DELETE FROM target before transfer (default: false)
 *   generateDDL   {boolean}   CREATE TABLE on target before transfer (default: false)
 *   dropIfExists  {boolean}   DROP TABLE before CREATE (only with generateDDL)
 *   errorMode     {string}    'abort' | 'skip'   (default: 'abort')
 *   dryRun        {boolean}   fetch source rows but don't write to target
 *   onProgress    {function}  (written, fetched, page) callback
 *   logger        {object}    { info, warn, error }
 */
class Pipe {
  constructor(srcConn, tgtConn, opts = {}) {
    this.src  = srcConn;
    this.tgt  = tgtConn;
    this.opts = opts;

    this.sourceTable  = opts.sourceTable  || null;
    this.targetTable  = opts.targetTable  || opts.sourceTable || null;
    this.sourceSQL    = opts.sourceSQL    || null;
    this.where        = opts.where        || null;
    this.mode         = opts.mode         || 'insert';
    this.keys         = opts.keys         || [];
    this.mapping      = opts.mapping      || {};
    this.batchSize    = opts.pageSize || opts.batchSize || 500;
    this.doTruncate   = opts.truncate     || false;
    // Dialect of the target DB — drives INSERT/MERGE syntax and literal formatting
    this.tgtDialect   = opts.tgtDialect instanceof Dialect
      ? opts.tgtDialect
      : Dialect.for(opts.tgtDialect || (tgtConn && tgtConn.dbType) || 'ibmi');
    this.doGenDDL     = opts.generateDDL  || false;
    this.dropIfExists = opts.dropIfExists || false;
    this.errorMode    = opts.errorMode    || ERROR_MODE.ABORT;
    this.dryRun       = opts.dryRun       || false;
    this.onProgress   = opts.onProgress   || null;
    this.log = opts.logger || {
      info:  (...a) => console.log(...a),
      warn:  (...a) => console.warn(...a),
      error: (...a) => console.error(...a),
    };
  }

  // ── public API ─────────────────────────────────────────────────────────────

  async run() {
    if (!this.sourceTable && !this.sourceSQL) {
      throw new Error('Pipe requires opts.sourceTable or opts.sourceSQL.');
    }
    if (!this.targetTable) {
      throw new Error('Pipe requires opts.targetTable (or opts.sourceTable as default).');
    }
    if (this.mode === 'merge' && this.keys.length === 0) {
      throw new Error('Pipe mode="merge" requires opts.keys.');
    }

    const result  = new PipeResult();
    result.dryRun = this.dryRun;
    const start   = Date.now();

    // ── Step 1: optional DDL on target ────────────────────────────────────────
    if (this.doGenDDL) {
      await this._executeDDL(result);
    }

    // ── Step 2: optional TRUNCATE on target ───────────────────────────────────
    if (this.doTruncate && !this.dryRun) {
      await this.tgt.execute(`DELETE FROM ${this.targetTable}`);
      result.truncated = true;
    }

    // ── Step 3: count total rows on source (for progress %) ──────────────────
    let totalRows = 0;
    try {
      const countSQL = this.sourceSQL
        ? `SELECT COUNT(*) AS CNT FROM (${this.sourceSQL}) AS _SRC`
        : `SELECT COUNT(*) AS CNT FROM ${this.sourceTable}` +
          (this.where ? ` WHERE ${this.where}` : '');
      const cr = await this.src.query(countSQL);
      totalRows = Number(cr.rows[0]?.CNT || cr.rows[0]?.cnt || 0);
    } catch {
      totalRows = 0; // non-fatal — progress % will be unavailable
    }

    // ── Step 4: paginated fetch → write ───────────────────────────────────────
    let offset = 0;
    let page   = 0;

    while (true) {
      const fetchSQL = this._buildFetchSQL(offset);
      let fetchResult;
      try {
        fetchResult = await this.src.query(fetchSQL);
      } catch (err) {
        const odbcDetail = err.odbcErrors
          ? err.odbcErrors.map(e => `[${e.state}] ${e.message}`).join('; ')
          : null;
        const detail = odbcDetail || err.message;
        throw new Error(`Fetch failed on source (page ${page + 1}):\n  SQL: ${fetchSQL}\n  ${detail}`);
      }
      const rows = fetchResult.rows;

      if (rows.length === 0) break;
      page++;

      // Determine column mapping on first page
      if (page === 1) {
        this._resolveColumns(fetchResult.columns);
      }

      // Write rows to target
      const writeOk = await this._writePage(rows, result, page);

      result.totalFetched += rows.length;
      result.pages = page;

      this._emitProgress(result.totalWritten, totalRows || result.totalFetched, page);

      if (!writeOk && this.errorMode === ERROR_MODE.ABORT) break;
      if (rows.length < this.batchSize) break;  // last page

      offset += rows.length;
    }

    result.elapsed = Date.now() - start;
    return result;
  }

  // ── internals ──────────────────────────────────────────────────────────────

  /**
   * Resolve effective source→dest column pairs from first page columns + mapping.
   * Stored as this._colPairs = [{ src, dest }]
   */
  _resolveColumns(columns) {
    this._colPairs = columns
      .map(c => ({
        src:  c.name,
        dest: this.mapping[c.name] !== undefined ? this.mapping[c.name] : c.name,
      }))
      .filter(p => p.dest);   // mapping to '' / null excludes column
  }

  _buildFetchSQL(offset) {
    // Use driver-specific pagination if source connection exposes paginateSQL
    const paginate = (inner) => {
      if (typeof this.src.paginateSQL === 'function') {
        return this.src.paginateSQL(inner, offset, this.batchSize);
      }
      // fallback: ANSI SQL:2008 OFFSET … FETCH FIRST (DB2, Oracle 12c+)
      return `SELECT * FROM (${inner}) AS _P FETCH FIRST ${this.batchSize} ROWS ONLY` +
             (offset > 0 ? ` OFFSET ${offset} ROWS` : '');
    };

    if (this.sourceSQL) return paginate(this.sourceSQL);

    const whereClause = this.where ? ` WHERE ${this.where}` : '';
    const baseSQL = `SELECT * FROM ${this.sourceTable}${whereClause}`;
    return paginate(baseSQL);
  }

  async _writePage(rows, result, page) {
    const destCols = this._colPairs.map(p => p.dest);
    const srcCols  = this._colPairs.map(p => p.src);

    for (const row of rows) {
      const values = srcCols.map(c => {
        const v = row[c];
        return (v === undefined || v === null) ? null : v;
      });

      let sql, execParams;
      if (this.mode === 'merge') {
        sql        = this._buildMergeSQL(destCols, values);
        execParams = [];   // upsert uses inline literals
      } else {
        const ins  = this.tgtDialect.insert(this.targetTable, destCols, values);
        sql        = ins.sql;
        execParams = ins.params;
      }

      if (this.dryRun) {
        result.totalWritten++;
        continue;
      }

      try {
        await this.tgt.execute(sql, execParams);
        result.totalWritten++;
      } catch (err) {
        const errMsg = err.message || String(err);
        result.errors.push({ page, sql: sql.slice(0, 120), error: errMsg });

        if (this.errorMode === ERROR_MODE.SKIP) {
          result.totalSkipped++;
          this.log.warn(`  ⚠ Row skipped — ${errMsg}`);
        } else {
          return false;  // ABORT
        }
      }
    }
    return true;
  }

  _buildMergeSQL(destCols, values) {
    return this.tgtDialect.upsert(this.targetTable, destCols, this.keys, values);
  }

  async _executeDDL(result) {
    // Need source describe for DDL
    if (!this.sourceTable) {
      this.log.warn('  DDL generation skipped: requires sourceTable (not sourceSQL).');
      return;
    }

    const [schema, table] = this.sourceTable.includes('.')
      ? this.sourceTable.split('.')
      : [null, this.sourceTable];

    const descResult = await this.src.describeTable(table, schema);

    if (descResult.rows.length === 0) {
      this.log.warn(`  DDL: no columns found for ${this.sourceTable}`);
      return;
    }

    const ddl = generateDDL(this.targetTable, descResult, this.tgtDialect);

    if (this.dryRun) {
      this.log.info('  [DRY RUN] DDL:\n' + ddl);
      result.ddlExecuted = true;
      return;
    }

    if (this.dropIfExists) {
      try {
        await this.tgt.execute(`DROP TABLE ${this.targetTable}`);
      } catch { /* table may not exist */ }
    }

    try {
      await this.tgt.execute(ddl.replace(/;\s*$/, ''));
      result.ddlExecuted = true;
    } catch (err) {
      if (this.errorMode === ERROR_MODE.ABORT) throw err;
      this.log.warn(`  DDL warning: ${err.message}`);
    }
  }

  _emitProgress(written, total, page) {
    if (this.onProgress) this.onProgress(written, total, page);
  }
}

// ─── private helpers ──────────────────────────────────────────────────────────

function _buildInsertSQL(table, destCols) {
  const cols  = destCols.join(', ');
  const marks = destCols.map(() => '?').join(', ');
  return `INSERT INTO ${table} (${cols}) VALUES (${marks})`;
}

function _sqlLiteral(val) {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number' || typeof val === 'boolean') return String(val);
  if (val instanceof Date) {
    const iso = val.toISOString();
    if (val.getHours() === 0 && val.getMinutes() === 0 && val.getSeconds() === 0) {
      return `'${iso.slice(0, 10)}'`;
    }
    return `TIMESTAMP '${iso.replace('T', ' ').replace('Z', '')}'`;
  }
  return `'${String(val).replace(/'/g, "''")}'`;
}

module.exports = { Pipe, PipeResult, generateDDL };
